//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTender_Status
    {
        public tblTender_Status()
        {
            this.tblTenders = new HashSet<tblTender>();
        }
    
        public int StatusID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<tblTender> tblTenders { get; set; }
    }
}
