//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTender_Drawing
    {
        public tblTender_Drawing()
        {
            this.tblTender_Item = new HashSet<tblTender_Item>();
        }
    
        public int DrawingID { get; set; }
        public int TenderID { get; set; }
        public string Title { get; set; }
        public string RevisionNo { get; set; }
        public string Comments { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual tblTender tblTender { get; set; }
        public virtual ICollection<tblTender_Item> tblTender_Item { get; set; }
    }
}
