//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTender_Step
    {
        public tblTender_Step()
        {
            this.tblTender_ActivityChildActivity = new HashSet<tblTender_ActivityChildActivity>();
            this.tblTender_ActivityContractor = new HashSet<tblTender_ActivityContractor>();
            this.tblTender_ActivityLabour = new HashSet<tblTender_ActivityLabour>();
            this.tblTender_ActivityMaterial = new HashSet<tblTender_ActivityMaterial>();
        }
    
        public int StepID { get; set; }
        public int TenderID { get; set; }
        public string Title { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<tblTender_ActivityChildActivity> tblTender_ActivityChildActivity { get; set; }
        public virtual ICollection<tblTender_ActivityContractor> tblTender_ActivityContractor { get; set; }
        public virtual ICollection<tblTender_ActivityLabour> tblTender_ActivityLabour { get; set; }
        public virtual ICollection<tblTender_ActivityMaterial> tblTender_ActivityMaterial { get; set; }
    }
}
