//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTender_Schedule
    {
        public tblTender_Schedule()
        {
            this.tblTender_Item = new HashSet<tblTender_Item>();
        }
    
        public int ScheduleID { get; set; }
        public int TenderID { get; set; }
        public string ClientCode { get; set; }
        public string ClientDescription { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int SortOrder { get; set; }
        public bool CanAllocate { get; set; }
        public string Comment { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<tblTender_Item> tblTender_Item { get; set; }
    }
}
