//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWEX_RHSTab
    {
        public tblWEX_RHSTab()
        {
            this.tblWEX_NTSecurityGroup = new HashSet<tblWEX_NTSecurityGroup>();
            this.tblWEX_TreeNodeType = new HashSet<tblWEX_TreeNodeType>();
        }
    
        public string RHSTabID { get; set; }
        public string Name { get; set; }
        public int Order { get; set; }
    
        public virtual ICollection<tblWEX_NTSecurityGroup> tblWEX_NTSecurityGroup { get; set; }
        public virtual ICollection<tblWEX_TreeNodeType> tblWEX_TreeNodeType { get; set; }
    }
}
