//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWEX_Tree
    {
        public tblWEX_Tree()
        {
            this.tblWEX_NTSecurityGroup = new HashSet<tblWEX_NTSecurityGroup>();
        }
    
        public string TreeID { get; set; }
        public string LHSTabID { get; set; }
        public int Order { get; set; }
        public string RootTreeNodeID { get; set; }
    
        public virtual tblWEX_LHSTab tblWEX_LHSTab { get; set; }
        public virtual tblWEX_TreeNode tblWEX_TreeNode { get; set; }
        public virtual ICollection<tblWEX_NTSecurityGroup> tblWEX_NTSecurityGroup { get; set; }
    }
}
