//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWEX_TreeNodeType
    {
        public tblWEX_TreeNodeType()
        {
            this.tblWEX_RHSTab = new HashSet<tblWEX_RHSTab>();
        }
    
        public string TreeNodeTypeID { get; set; }
    
        public virtual ICollection<tblWEX_RHSTab> tblWEX_RHSTab { get; set; }
    }
}
