//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WalzExplorerEntities : DbContext
    {
        public WalzExplorerEntities()
            : base("name=WalzExplorerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblPerson_Person> tblPerson_Person { get; set; }
        public virtual DbSet<tblProject_Project> tblProject_Project { get; set; }
        public virtual DbSet<tblTender> tblTenders { get; set; }
        public virtual DbSet<tblTender_Activity> tblTender_Activity { get; set; }
        public virtual DbSet<tblTender_ActivityChildActivity> tblTender_ActivityChildActivity { get; set; }
        public virtual DbSet<tblTender_ActivityContractor> tblTender_ActivityContractor { get; set; }
        public virtual DbSet<tblTender_ActivityLabour> tblTender_ActivityLabour { get; set; }
        public virtual DbSet<tblTender_ActivityMaterial> tblTender_ActivityMaterial { get; set; }
        public virtual DbSet<tblTender_Contractor> tblTender_Contractor { get; set; }
        public virtual DbSet<tblTender_ContractorType> tblTender_ContractorType { get; set; }
        public virtual DbSet<tblTender_Drawing> tblTender_Drawing { get; set; }
        public virtual DbSet<tblTender_Item> tblTender_Item { get; set; }
        public virtual DbSet<tblTender_LabourStandard> tblTender_LabourStandard { get; set; }
        public virtual DbSet<tblTender_Material> tblTender_Material { get; set; }
        public virtual DbSet<tblTender_Schedule> tblTender_Schedule { get; set; }
        public virtual DbSet<tblTender_Status> tblTender_Status { get; set; }
        public virtual DbSet<tblTender_Step> tblTender_Step { get; set; }
        public virtual DbSet<tblTender_Supplier> tblTender_Supplier { get; set; }
        public virtual DbSet<tblTender_Supplier_Material> tblTender_Supplier_Material { get; set; }
        public virtual DbSet<tblTender_UnitOfMeasure> tblTender_UnitOfMeasure { get; set; }
        public virtual DbSet<tblTender_WorkGroup> tblTender_WorkGroup { get; set; }
        public virtual DbSet<tblTender_WorkGroupHeader> tblTender_WorkGroupHeader { get; set; }
        public virtual DbSet<tblTender_WorkGroupItem> tblTender_WorkGroupItem { get; set; }
        public virtual DbSet<tblWEX_LHSTab> tblWEX_LHSTab { get; set; }
        public virtual DbSet<tblWEX_NTSecurityGroup> tblWEX_NTSecurityGroup { get; set; }
        public virtual DbSet<tblWEX_RHSTab> tblWEX_RHSTab { get; set; }
        public virtual DbSet<tblWEX_Tree> tblWEX_Tree { get; set; }
        public virtual DbSet<tblWEX_TreeNode> tblWEX_TreeNode { get; set; }
        public virtual DbSet<tblWEX_TreeNodeType> tblWEX_TreeNodeType { get; set; }
    }
}
