//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServicesEntities : DbContext
    {
        public ServicesEntities()
            : base("name=ServicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblIntegrity_Check> tblIntegrity_Check { get; set; }
        public virtual DbSet<tblIntegrity_EmailRecipient> tblIntegrity_EmailRecipient { get; set; }
        public virtual DbSet<tblIntegrity_Issue> tblIntegrity_Issue { get; set; }
        public virtual DbSet<tblIntegrity_Issue_temp> tblIntegrity_Issue_temp { get; set; }
        public virtual DbSet<tblIntegrity_System> tblIntegrity_System { get; set; }
        public virtual DbSet<tblLog> tblLogs { get; set; }
        public virtual DbSet<tblLog_Column> tblLog_Column { get; set; }
        public virtual DbSet<tblLog_Database> tblLog_Database { get; set; }
        public virtual DbSet<tblLog_Operation> tblLog_Operation { get; set; }
        public virtual DbSet<tblLog_Table> tblLog_Table { get; set; }
        public virtual DbSet<tblLog_User> tblLog_User { get; set; }
        public virtual DbSet<tblFeedback_Application> tblFeedback_Application { get; set; }
        public virtual DbSet<tblFeedback_Item> tblFeedback_Item { get; set; }
        public virtual DbSet<tblFeedback_Status> tblFeedback_Status { get; set; }
        public virtual DbSet<tblFeedback_Type> tblFeedback_Type { get; set; }
    }
}
