//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEventLog
    {
        public int EventLogID { get; set; }
        public string UserID { get; set; }
        public string ApplicationID { get; set; }
        public string OperationID { get; set; }
        public System.DateTime DateTime { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
