//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeedback
    {
        public int ItemID { get; set; }
        public int TypeID { get; set; }
        public int StatusID { get; set; }
        public int ApplicationID { get; set; }
        public string SubApplication { get; set; }
        public string User { get; set; }
        public string Title { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
    
        public virtual tblFeedback_Application tblFeedback_Application { get; set; }
        public virtual tblFeedback_Type tblFeedback_Type { get; set; }
        public virtual tblFeedback_Status tblFeedback_Status { get; set; }
    }
}
