//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeedback_Application
    {
        public tblFeedback_Application()
        {
            this.tblFeedback_Item = new HashSet<tblFeedback_Item>();
        }
    
        public int ApplicationID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<tblFeedback_Item> tblFeedback_Item { get; set; }
    }
}
