//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeedback_Status
    {
        public tblFeedback_Status()
        {
            this.tblFeedbacks = new HashSet<tblFeedback>();
        }
    
        public int StatusID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<tblFeedback> tblFeedbacks { get; set; }
    }
}
