//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblFavourite : ModelBase
    {
        private int _favouriteID;
    	public int FavouriteID 
    	{ 
    		get { return _favouriteID; } 
    		set { SetProperty(ref _favouriteID, value); } 
    	}
    
        private int _personID;
    	public int PersonID 
    	{ 
    		get { return _personID; } 
    		set { SetProperty(ref _personID, value); } 
    	}
    
        private int _typeID;
    	public int TypeID 
    	{ 
    		get { return _typeID; } 
    		set { SetProperty(ref _typeID, value); } 
    	}
    
        private int _identifier;
    	public int Identifier 
    	{ 
    		get { return _identifier; } 
    		set { SetProperty(ref _identifier, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    }
}
