//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIntegrity_EmailRecipient
    {
        public tblIntegrity_EmailRecipient()
        {
            this.tblIntegrity_System = new HashSet<tblIntegrity_System>();
        }
    
        public int EmailRecipientID { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual ICollection<tblIntegrity_System> tblIntegrity_System { get; set; }
    }
}
