//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIntegrity_Check
    {
        public tblIntegrity_Check()
        {
            this.tblIntegrity_Issue = new HashSet<tblIntegrity_Issue>();
            this.tblIntegrity_Issue_temp = new HashSet<tblIntegrity_Issue_temp>();
        }
    
        public int CheckID { get; set; }
        public int SystemID { get; set; }
        public string StoredProcedure { get; set; }
        public string Title { get; set; }
        public string IssueObjectType { get; set; }
        public string Solution { get; set; }
        public string InfoField1Title { get; set; }
        public string InfoField2Title { get; set; }
    
        public virtual tblIntegrity_System tblIntegrity_System { get; set; }
        public virtual ICollection<tblIntegrity_Issue> tblIntegrity_Issue { get; set; }
        public virtual ICollection<tblIntegrity_Issue_temp> tblIntegrity_Issue_temp { get; set; }
    }
}
