//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLog_Database
    {
        public tblLog_Database()
        {
            this.tblLogs = new HashSet<tblLog>();
        }
    
        public int DatabaseID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<tblLog> tblLogs { get; set; }
    }
}
