//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblProject_History : ModelBase
    {
        public tblProject_History()
        {
            this.tblProject_HistoryCritical = new HashSet<tblProject_HistoryCritical>();
            this.tblProject_HistoryMilestone = new HashSet<tblProject_HistoryMilestone>();
            this.tblProject_HistoryDollars = new HashSet<tblProject_HistoryDollars>();
            this.tblProject_HistoryIncident = new HashSet<tblProject_HistoryIncident>();
            this.tblProject_HistoryHours = new HashSet<tblProject_HistoryHours>();
            this.tblProject_HistoryNCR = new HashSet<tblProject_HistoryNCR>();
            this.tblProject_HistoryRFI = new HashSet<tblProject_HistoryRFI>();
        }
    
        private int _historyID;
    	public int HistoryID 
    	{ 
    		get { return _historyID; } 
    		set { SetProperty(ref _historyID, value); } 
    	}
    
        private int _projectID;
    	public int ProjectID 
    	{ 
    		get { return _projectID; } 
    		set { SetProperty(ref _projectID, value); } 
    	}
    
        private string _aXProjectID;
    	public string AXProjectID 
    	{ 
    		get { return _aXProjectID; } 
    		set { SetProperty(ref _aXProjectID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private string _status;
    	public string Status 
    	{ 
    		get { return _status; } 
    		set { SetProperty(ref _status, value); } 
    	}
    
        private Nullable<int> _grossProfit;
    	public Nullable<int> GrossProfit 
    	{ 
    		get { return _grossProfit; } 
    		set { SetProperty(ref _grossProfit, value); } 
    	}
    
        private string _aXJobNo;
    	public string AXJobNo 
    	{ 
    		get { return _aXJobNo; } 
    		set { SetProperty(ref _aXJobNo, value); } 
    	}
    
        private string _contractType;
    	public string ContractType 
    	{ 
    		get { return _contractType; } 
    		set { SetProperty(ref _contractType, value); } 
    	}
    
        private Nullable<System.DateTime> _weekEnding;
    	public Nullable<System.DateTime> WeekEnding 
    	{ 
    		get { return _weekEnding; } 
    		set { SetProperty(ref _weekEnding, value); } 
    	}
    
        private Nullable<System.DateTime> _keyDatesAward;
    	public Nullable<System.DateTime> KeyDatesAward 
    	{ 
    		get { return _keyDatesAward; } 
    		set { SetProperty(ref _keyDatesAward, value); } 
    	}
    
        private Nullable<System.DateTime> _keyDatesOriginalPC;
    	public Nullable<System.DateTime> KeyDatesOriginalPC 
    	{ 
    		get { return _keyDatesOriginalPC; } 
    		set { SetProperty(ref _keyDatesOriginalPC, value); } 
    	}
    
        private Nullable<System.DateTime> _keyDatesApprovedPC;
    	public Nullable<System.DateTime> KeyDatesApprovedPC 
    	{ 
    		get { return _keyDatesApprovedPC; } 
    		set { SetProperty(ref _keyDatesApprovedPC, value); } 
    	}
    
        private Nullable<System.DateTime> _keyDatesForecastPC;
    	public Nullable<System.DateTime> KeyDatesForecastPC 
    	{ 
    		get { return _keyDatesForecastPC; } 
    		set { SetProperty(ref _keyDatesForecastPC, value); } 
    	}
    
        private string _keyDatesRiskOpp;
    	public string KeyDatesRiskOpp 
    	{ 
    		get { return _keyDatesRiskOpp; } 
    		set { SetProperty(ref _keyDatesRiskOpp, value); } 
    	}
    
        private Nullable<int> _durationActual;
    	public Nullable<int> DurationActual 
    	{ 
    		get { return _durationActual; } 
    		set { SetProperty(ref _durationActual, value); } 
    	}
    
        private Nullable<int> _durationOriginal;
    	public Nullable<int> DurationOriginal 
    	{ 
    		get { return _durationOriginal; } 
    		set { SetProperty(ref _durationOriginal, value); } 
    	}
    
        private Nullable<int> _durationApproved;
    	public Nullable<int> DurationApproved 
    	{ 
    		get { return _durationApproved; } 
    		set { SetProperty(ref _durationApproved, value); } 
    	}
    
        private Nullable<int> _durationForecast;
    	public Nullable<int> DurationForecast 
    	{ 
    		get { return _durationForecast; } 
    		set { SetProperty(ref _durationForecast, value); } 
    	}
    
        private string _durationRiskOpp;
    	public string DurationRiskOpp 
    	{ 
    		get { return _durationRiskOpp; } 
    		set { SetProperty(ref _durationRiskOpp, value); } 
    	}
    
        private Nullable<int> _completeActual;
    	public Nullable<int> CompleteActual 
    	{ 
    		get { return _completeActual; } 
    		set { SetProperty(ref _completeActual, value); } 
    	}
    
        private Nullable<int> _completeBaseline;
    	public Nullable<int> CompleteBaseline 
    	{ 
    		get { return _completeBaseline; } 
    		set { SetProperty(ref _completeBaseline, value); } 
    	}
    
        private Nullable<int> _completeApprovedBaseline;
    	public Nullable<int> CompleteApprovedBaseline 
    	{ 
    		get { return _completeApprovedBaseline; } 
    		set { SetProperty(ref _completeApprovedBaseline, value); } 
    	}
    
        private Nullable<int> _completeForecast;
    	public Nullable<int> CompleteForecast 
    	{ 
    		get { return _completeForecast; } 
    		set { SetProperty(ref _completeForecast, value); } 
    	}
    
        private string _completeRiskOpp;
    	public string CompleteRiskOpp 
    	{ 
    		get { return _completeRiskOpp; } 
    		set { SetProperty(ref _completeRiskOpp, value); } 
    	}
    
        private int _statusID;
    	public int StatusID 
    	{ 
    		get { return _statusID; } 
    		set { SetProperty(ref _statusID, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
        private string _statusActionsTaken;
    	public string StatusActionsTaken 
    	{ 
    		get { return _statusActionsTaken; } 
    		set { SetProperty(ref _statusActionsTaken, value); } 
    	}
    
        private string _resourcesPFRiskOpp;
    	public string ResourcesPFRiskOpp 
    	{ 
    		get { return _resourcesPFRiskOpp; } 
    		set { SetProperty(ref _resourcesPFRiskOpp, value); } 
    	}
    
        private string _resourcesEACRiskOpp;
    	public string ResourcesEACRiskOpp 
    	{ 
    		get { return _resourcesEACRiskOpp; } 
    		set { SetProperty(ref _resourcesEACRiskOpp, value); } 
    	}
    
        private Nullable<double> _summaryContractValueOriginal;
    	public Nullable<double> SummaryContractValueOriginal 
    	{ 
    		get { return _summaryContractValueOriginal; } 
    		set { SetProperty(ref _summaryContractValueOriginal, value); } 
    	}
    
        private Nullable<double> _summaryContactValueApproved;
    	public Nullable<double> SummaryContactValueApproved 
    	{ 
    		get { return _summaryContactValueApproved; } 
    		set { SetProperty(ref _summaryContactValueApproved, value); } 
    	}
    
        private string _summaryContactValueRiskOpp;
    	public string SummaryContactValueRiskOpp 
    	{ 
    		get { return _summaryContactValueRiskOpp; } 
    		set { SetProperty(ref _summaryContactValueRiskOpp, value); } 
    	}
    
        private Nullable<double> _summaryAtCompletionBudget;
    	public Nullable<double> SummaryAtCompletionBudget 
    	{ 
    		get { return _summaryAtCompletionBudget; } 
    		set { SetProperty(ref _summaryAtCompletionBudget, value); } 
    	}
    
        private Nullable<double> _summaryAtCompletionEstimate;
    	public Nullable<double> SummaryAtCompletionEstimate 
    	{ 
    		get { return _summaryAtCompletionEstimate; } 
    		set { SetProperty(ref _summaryAtCompletionEstimate, value); } 
    	}
    
        private string _summaryAtCompletionRiskOpp;
    	public string SummaryAtCompletionRiskOpp 
    	{ 
    		get { return _summaryAtCompletionRiskOpp; } 
    		set { SetProperty(ref _summaryAtCompletionRiskOpp, value); } 
    	}
    
        private Nullable<double> _summaryCPI;
    	public Nullable<double> SummaryCPI 
    	{ 
    		get { return _summaryCPI; } 
    		set { SetProperty(ref _summaryCPI, value); } 
    	}
    
        private Nullable<double> _summarySPI;
    	public Nullable<double> SummarySPI 
    	{ 
    		get { return _summarySPI; } 
    		set { SetProperty(ref _summarySPI, value); } 
    	}
    
        private string _summarySPICPIRiskOpp;
    	public string SummarySPICPIRiskOpp 
    	{ 
    		get { return _summarySPICPIRiskOpp; } 
    		set { SetProperty(ref _summarySPICPIRiskOpp, value); } 
    	}
    
        private Nullable<double> _budgetBudget;
    	public Nullable<double> BudgetBudget 
    	{ 
    		get { return _budgetBudget; } 
    		set { SetProperty(ref _budgetBudget, value); } 
    	}
    
        private Nullable<double> _budgetPlanned;
    	public Nullable<double> BudgetPlanned 
    	{ 
    		get { return _budgetPlanned; } 
    		set { SetProperty(ref _budgetPlanned, value); } 
    	}
    
        private Nullable<double> _budgetEarned;
    	public Nullable<double> BudgetEarned 
    	{ 
    		get { return _budgetEarned; } 
    		set { SetProperty(ref _budgetEarned, value); } 
    	}
    
        private Nullable<double> _budgetActual;
    	public Nullable<double> BudgetActual 
    	{ 
    		get { return _budgetActual; } 
    		set { SetProperty(ref _budgetActual, value); } 
    	}
    
        private Nullable<double> _budgetCV;
    	public Nullable<double> BudgetCV 
    	{ 
    		get { return _budgetCV; } 
    		set { SetProperty(ref _budgetCV, value); } 
    	}
    
        private Nullable<double> _budgetSV;
    	public Nullable<double> BudgetSV 
    	{ 
    		get { return _budgetSV; } 
    		set { SetProperty(ref _budgetSV, value); } 
    	}
    
        private Nullable<double> _budgetCPI;
    	public Nullable<double> BudgetCPI 
    	{ 
    		get { return _budgetCPI; } 
    		set { SetProperty(ref _budgetCPI, value); } 
    	}
    
        private string _budgetRiskOpp;
    	public string BudgetRiskOpp 
    	{ 
    		get { return _budgetRiskOpp; } 
    		set { SetProperty(ref _budgetRiskOpp, value); } 
    	}
    
        private byte[] _statusGantt;
    	public byte[] StatusGantt 
    	{ 
    		get { return _statusGantt; } 
    		set { SetProperty(ref _statusGantt, value); } 
    	}
    
        private string _statusRiskOpp;
    	public string StatusRiskOpp 
    	{ 
    		get { return _statusRiskOpp; } 
    		set { SetProperty(ref _statusRiskOpp, value); } 
    	}
    
        private Nullable<double> _budgetContractTotal;
    	public Nullable<double> BudgetContractTotal 
    	{ 
    		get { return _budgetContractTotal; } 
    		set { SetProperty(ref _budgetContractTotal, value); } 
    	}
    
        private Nullable<double> _budgetContractMarginDollars;
    	public Nullable<double> BudgetContractMarginDollars 
    	{ 
    		get { return _budgetContractMarginDollars; } 
    		set { SetProperty(ref _budgetContractMarginDollars, value); } 
    	}
    
        private Nullable<double> _budgetContractMarginPercent;
    	public Nullable<double> BudgetContractMarginPercent 
    	{ 
    		get { return _budgetContractMarginPercent; } 
    		set { SetProperty(ref _budgetContractMarginPercent, value); } 
    	}
    
        private string _rFIForeseenIssuesActions;
    	public string RFIForeseenIssuesActions 
    	{ 
    		get { return _rFIForeseenIssuesActions; } 
    		set { SetProperty(ref _rFIForeseenIssuesActions, value); } 
    	}
    
        private string _qualityForeseenIssuesActions;
    	public string QualityForeseenIssuesActions 
    	{ 
    		get { return _qualityForeseenIssuesActions; } 
    		set { SetProperty(ref _qualityForeseenIssuesActions, value); } 
    	}
    
        private string _environmentForeseenIssuesActions;
    	public string EnvironmentForeseenIssuesActions 
    	{ 
    		get { return _environmentForeseenIssuesActions; } 
    		set { SetProperty(ref _environmentForeseenIssuesActions, value); } 
    	}
    
        private string _other;
    	public string Other 
    	{ 
    		get { return _other; } 
    		set { SetProperty(ref _other, value); } 
    	}
    
        private System.DateTime _periodStart;
    	public System.DateTime PeriodStart 
    	{ 
    		get { return _periodStart; } 
    		set { SetProperty(ref _periodStart, value); } 
    	}
    
        private System.DateTime _periodEnd;
    	public System.DateTime PeriodEnd 
    	{ 
    		get { return _periodEnd; } 
    		set { SetProperty(ref _periodEnd, value); } 
    	}
    
        private string _customer;
    	public string Customer 
    	{ 
    		get { return _customer; } 
    		set { SetProperty(ref _customer, value); } 
    	}
    
        private Nullable<int> _timeRatingID;
    	public Nullable<int> TimeRatingID 
    	{ 
    		get { return _timeRatingID; } 
    		set { SetProperty(ref _timeRatingID, value); } 
    	}
    
        private Nullable<int> _hoursRatingID;
    	public Nullable<int> HoursRatingID 
    	{ 
    		get { return _hoursRatingID; } 
    		set { SetProperty(ref _hoursRatingID, value); } 
    	}
    
        private Nullable<int> _costRatingID;
    	public Nullable<int> CostRatingID 
    	{ 
    		get { return _costRatingID; } 
    		set { SetProperty(ref _costRatingID, value); } 
    	}
    
        private Nullable<int> _safetyRatingID;
    	public Nullable<int> SafetyRatingID 
    	{ 
    		get { return _safetyRatingID; } 
    		set { SetProperty(ref _safetyRatingID, value); } 
    	}
    
        private Nullable<int> _qualityRatingID;
    	public Nullable<int> QualityRatingID 
    	{ 
    		get { return _qualityRatingID; } 
    		set { SetProperty(ref _qualityRatingID, value); } 
    	}
    
        private string _pMSummaryNotes;
    	public string PMSummaryNotes 
    	{ 
    		get { return _pMSummaryNotes; } 
    		set { SetProperty(ref _pMSummaryNotes, value); } 
    	}
    
        private string _oMSummaryNotes;
    	public string OMSummaryNotes 
    	{ 
    		get { return _oMSummaryNotes; } 
    		set { SetProperty(ref _oMSummaryNotes, value); } 
    	}
    
        private Nullable<int> _safetyLTI;
    	public Nullable<int> SafetyLTI 
    	{ 
    		get { return _safetyLTI; } 
    		set { SetProperty(ref _safetyLTI, value); } 
    	}
    
        private Nullable<int> _safetyMTI;
    	public Nullable<int> SafetyMTI 
    	{ 
    		get { return _safetyMTI; } 
    		set { SetProperty(ref _safetyMTI, value); } 
    	}
    
        private Nullable<int> _safetyFAI;
    	public Nullable<int> SafetyFAI 
    	{ 
    		get { return _safetyFAI; } 
    		set { SetProperty(ref _safetyFAI, value); } 
    	}
    
        private Nullable<int> _safetyNearMiss;
    	public Nullable<int> SafetyNearMiss 
    	{ 
    		get { return _safetyNearMiss; } 
    		set { SetProperty(ref _safetyNearMiss, value); } 
    	}
    
        private Nullable<int> _safetyLTIFR;
    	public Nullable<int> SafetyLTIFR 
    	{ 
    		get { return _safetyLTIFR; } 
    		set { SetProperty(ref _safetyLTIFR, value); } 
    	}
    
        private Nullable<int> _safetyTRIFR;
    	public Nullable<int> SafetyTRIFR 
    	{ 
    		get { return _safetyTRIFR; } 
    		set { SetProperty(ref _safetyTRIFR, value); } 
    	}
    
        private Nullable<int> _safetyHours;
    	public Nullable<int> SafetyHours 
    	{ 
    		get { return _safetyHours; } 
    		set { SetProperty(ref _safetyHours, value); } 
    	}
    
        private Nullable<double> _summaryHousBudget;
    	public Nullable<double> SummaryHousBudget 
    	{ 
    		get { return _summaryHousBudget; } 
    		set { SetProperty(ref _summaryHousBudget, value); } 
    	}
    
        private Nullable<double> _summaryCostBudget;
    	public Nullable<double> SummaryCostBudget 
    	{ 
    		get { return _summaryCostBudget; } 
    		set { SetProperty(ref _summaryCostBudget, value); } 
    	}
    
        private Nullable<int> _projectManagerSignID;
    	public Nullable<int> ProjectManagerSignID 
    	{ 
    		get { return _projectManagerSignID; } 
    		set { SetProperty(ref _projectManagerSignID, value); } 
    	}
    
        private Nullable<System.DateTime> _projectManagerSignDate;
    	public Nullable<System.DateTime> ProjectManagerSignDate 
    	{ 
    		get { return _projectManagerSignDate; } 
    		set { SetProperty(ref _projectManagerSignDate, value); } 
    	}
    
        private Nullable<int> _operationsManagerSignID;
    	public Nullable<int> OperationsManagerSignID 
    	{ 
    		get { return _operationsManagerSignID; } 
    		set { SetProperty(ref _operationsManagerSignID, value); } 
    	}
    
        private Nullable<System.DateTime> _operationsManagerSignDate;
    	public Nullable<System.DateTime> OperationsManagerSignDate 
    	{ 
    		get { return _operationsManagerSignDate; } 
    		set { SetProperty(ref _operationsManagerSignDate, value); } 
    	}
    
        private string _timeComments;
    	public string TimeComments 
    	{ 
    		get { return _timeComments; } 
    		set { SetProperty(ref _timeComments, value); } 
    	}
    
        private string _hoursComments;
    	public string HoursComments 
    	{ 
    		get { return _hoursComments; } 
    		set { SetProperty(ref _hoursComments, value); } 
    	}
    
        private string _costComments;
    	public string CostComments 
    	{ 
    		get { return _costComments; } 
    		set { SetProperty(ref _costComments, value); } 
    	}
    
        private string _safetyComments;
    	public string SafetyComments 
    	{ 
    		get { return _safetyComments; } 
    		set { SetProperty(ref _safetyComments, value); } 
    	}
    
        private string _qualityComments;
    	public string QualityComments 
    	{ 
    		get { return _qualityComments; } 
    		set { SetProperty(ref _qualityComments, value); } 
    	}
    
        private Nullable<int> _basicRatingID;
    	public Nullable<int> BasicRatingID 
    	{ 
    		get { return _basicRatingID; } 
    		set { SetProperty(ref _basicRatingID, value); } 
    	}
    
        private string _basicComments;
    	public string BasicComments 
    	{ 
    		get { return _basicComments; } 
    		set { SetProperty(ref _basicComments, value); } 
    	}
    
        private Nullable<double> _basicCostBudget;
    	public Nullable<double> BasicCostBudget 
    	{ 
    		get { return _basicCostBudget; } 
    		set { SetProperty(ref _basicCostBudget, value); } 
    	}
    
        private Nullable<double> _basicCostToReportDate;
    	public Nullable<double> BasicCostToReportDate 
    	{ 
    		get { return _basicCostToReportDate; } 
    		set { SetProperty(ref _basicCostToReportDate, value); } 
    	}
    
        private Nullable<double> _basicCostAtCompletion;
    	public Nullable<double> BasicCostAtCompletion 
    	{ 
    		get { return _basicCostAtCompletion; } 
    		set { SetProperty(ref _basicCostAtCompletion, value); } 
    	}
    
    
        public virtual tblProject_HistoryStatus tblProject_HistoryStatus { get; set; }
        public virtual ICollection<tblProject_HistoryCritical> tblProject_HistoryCritical { get; set; }
        public virtual ICollection<tblProject_HistoryMilestone> tblProject_HistoryMilestone { get; set; }
        public virtual tblProject tblProject { get; set; }
        public virtual tblProject_HistoryRating tblProject_HistoryRating { get; set; }
        public virtual tblProject_HistoryRating tblProject_HistoryRating1 { get; set; }
        public virtual tblProject_HistoryRating tblProject_HistoryRating2 { get; set; }
        public virtual tblProject_HistoryRating tblProject_HistoryRating3 { get; set; }
        public virtual tblProject_HistoryRating tblProject_HistoryRating4 { get; set; }
        public virtual ICollection<tblProject_HistoryDollars> tblProject_HistoryDollars { get; set; }
        public virtual ICollection<tblProject_HistoryIncident> tblProject_HistoryIncident { get; set; }
        public virtual ICollection<tblProject_HistoryHours> tblProject_HistoryHours { get; set; }
        public virtual ICollection<tblProject_HistoryNCR> tblProject_HistoryNCR { get; set; }
        public virtual ICollection<tblProject_HistoryRFI> tblProject_HistoryRFI { get; set; }
    }
}
