//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblProject : ModelBase
    {
        public tblProject()
        {
            this.tblProject_History = new HashSet<tblProject_History>();
        }
    
        private int _projectID;
    	public int ProjectID 
    	{ 
    		get { return _projectID; } 
    		set { SetProperty(ref _projectID, value); } 
    	}
    
        private string _aXProjectID;
    	public string AXProjectID 
    	{ 
    		get { return _aXProjectID; } 
    		set { SetProperty(ref _aXProjectID, value); } 
    	}
    
        private string _aXDataAreaID;
    	public string AXDataAreaID 
    	{ 
    		get { return _aXDataAreaID; } 
    		set { SetProperty(ref _aXDataAreaID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private int _managerID;
    	public int ManagerID 
    	{ 
    		get { return _managerID; } 
    		set { SetProperty(ref _managerID, value); } 
    	}
    
        private int _operationsManagerID;
    	public int OperationsManagerID 
    	{ 
    		get { return _operationsManagerID; } 
    		set { SetProperty(ref _operationsManagerID, value); } 
    	}
    
        private int _statusID;
    	public int StatusID 
    	{ 
    		get { return _statusID; } 
    		set { SetProperty(ref _statusID, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual tblPerson tblPerson { get; set; }
        public virtual tblPerson tblPerson1 { get; set; }
        public virtual ICollection<tblProject_History> tblProject_History { get; set; }
        public virtual tblProject_Status tblProject_Status { get; set; }
    }
}
