//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblProject_History : ModelBase
    {
        public tblProject_History()
        {
            this.tblProject_HistoryCritical = new HashSet<tblProject_HistoryCritical>();
            this.tblProject_HistoryManHours = new HashSet<tblProject_HistoryManHours>();
            this.tblProject_HistoryMilestone = new HashSet<tblProject_HistoryMilestone>();
        }
    
        private int _historyID;
    	public int HistoryID 
    	{ 
    		get { return _historyID; } 
    		set { SetProperty(ref _historyID, value); } 
    	}
    
        private int _projectID;
    	public int ProjectID 
    	{ 
    		get { return _projectID; } 
    		set { SetProperty(ref _projectID, value); } 
    	}
    
        private System.DateTime _period;
    	public System.DateTime Period 
    	{ 
    		get { return _period; } 
    		set { SetProperty(ref _period, value); } 
    	}
    
        private string _aXProjectID;
    	public string AXProjectID 
    	{ 
    		get { return _aXProjectID; } 
    		set { SetProperty(ref _aXProjectID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private string _status;
    	public string Status 
    	{ 
    		get { return _status; } 
    		set { SetProperty(ref _status, value); } 
    	}
    
        private Nullable<int> _grossProfit;
    	public Nullable<int> GrossProfit 
    	{ 
    		get { return _grossProfit; } 
    		set { SetProperty(ref _grossProfit, value); } 
    	}
    
        private string _aXJobNo;
    	public string AXJobNo 
    	{ 
    		get { return _aXJobNo; } 
    		set { SetProperty(ref _aXJobNo, value); } 
    	}
    
        private string _contractType;
    	public string ContractType 
    	{ 
    		get { return _contractType; } 
    		set { SetProperty(ref _contractType, value); } 
    	}
    
        private string _client;
    	public string Client 
    	{ 
    		get { return _client; } 
    		set { SetProperty(ref _client, value); } 
    	}
    
        private Nullable<System.DateTime> _date;
    	public Nullable<System.DateTime> Date 
    	{ 
    		get { return _date; } 
    		set { SetProperty(ref _date, value); } 
    	}
    
        private Nullable<System.DateTime> _weekEnding;
    	public Nullable<System.DateTime> WeekEnding 
    	{ 
    		get { return _weekEnding; } 
    		set { SetProperty(ref _weekEnding, value); } 
    	}
    
        private Nullable<System.DateTime> _keyDatesAward;
    	public Nullable<System.DateTime> KeyDatesAward 
    	{ 
    		get { return _keyDatesAward; } 
    		set { SetProperty(ref _keyDatesAward, value); } 
    	}
    
        private Nullable<System.DateTime> _keyDatesOriginalPC;
    	public Nullable<System.DateTime> KeyDatesOriginalPC 
    	{ 
    		get { return _keyDatesOriginalPC; } 
    		set { SetProperty(ref _keyDatesOriginalPC, value); } 
    	}
    
        private Nullable<System.DateTime> _keyDatesApprovedPC;
    	public Nullable<System.DateTime> KeyDatesApprovedPC 
    	{ 
    		get { return _keyDatesApprovedPC; } 
    		set { SetProperty(ref _keyDatesApprovedPC, value); } 
    	}
    
        private Nullable<System.DateTime> _keyDatesForecastPC;
    	public Nullable<System.DateTime> KeyDatesForecastPC 
    	{ 
    		get { return _keyDatesForecastPC; } 
    		set { SetProperty(ref _keyDatesForecastPC, value); } 
    	}
    
        private string _keyDatesRiskOpp;
    	public string KeyDatesRiskOpp 
    	{ 
    		get { return _keyDatesRiskOpp; } 
    		set { SetProperty(ref _keyDatesRiskOpp, value); } 
    	}
    
        private Nullable<int> _durationActual;
    	public Nullable<int> DurationActual 
    	{ 
    		get { return _durationActual; } 
    		set { SetProperty(ref _durationActual, value); } 
    	}
    
        private Nullable<int> _durationOriginal;
    	public Nullable<int> DurationOriginal 
    	{ 
    		get { return _durationOriginal; } 
    		set { SetProperty(ref _durationOriginal, value); } 
    	}
    
        private Nullable<int> _durationApproved;
    	public Nullable<int> DurationApproved 
    	{ 
    		get { return _durationApproved; } 
    		set { SetProperty(ref _durationApproved, value); } 
    	}
    
        private Nullable<int> _durationForecast;
    	public Nullable<int> DurationForecast 
    	{ 
    		get { return _durationForecast; } 
    		set { SetProperty(ref _durationForecast, value); } 
    	}
    
        private string _durationRiskOpp;
    	public string DurationRiskOpp 
    	{ 
    		get { return _durationRiskOpp; } 
    		set { SetProperty(ref _durationRiskOpp, value); } 
    	}
    
        private Nullable<int> _completeActual;
    	public Nullable<int> CompleteActual 
    	{ 
    		get { return _completeActual; } 
    		set { SetProperty(ref _completeActual, value); } 
    	}
    
        private Nullable<int> _completeBaseline;
    	public Nullable<int> CompleteBaseline 
    	{ 
    		get { return _completeBaseline; } 
    		set { SetProperty(ref _completeBaseline, value); } 
    	}
    
        private Nullable<int> _completeApprovedBaseline;
    	public Nullable<int> CompleteApprovedBaseline 
    	{ 
    		get { return _completeApprovedBaseline; } 
    		set { SetProperty(ref _completeApprovedBaseline, value); } 
    	}
    
        private Nullable<int> _completeForecast;
    	public Nullable<int> CompleteForecast 
    	{ 
    		get { return _completeForecast; } 
    		set { SetProperty(ref _completeForecast, value); } 
    	}
    
        private string _completeRiskOpp;
    	public string CompleteRiskOpp 
    	{ 
    		get { return _completeRiskOpp; } 
    		set { SetProperty(ref _completeRiskOpp, value); } 
    	}
    
        private int _statusID;
    	public int StatusID 
    	{ 
    		get { return _statusID; } 
    		set { SetProperty(ref _statusID, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual tblProject_HistoryStatus tblProject_HistoryStatus { get; set; }
        public virtual ICollection<tblProject_HistoryCritical> tblProject_HistoryCritical { get; set; }
        public virtual ICollection<tblProject_HistoryManHours> tblProject_HistoryManHours { get; set; }
        public virtual ICollection<tblProject_HistoryMilestone> tblProject_HistoryMilestone { get; set; }
        public virtual tblProject tblProject { get; set; }
    }
}
