//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblProject_HistoryManHours : ModelBase
    {
        private int _historyID;
    	public int HistoryID 
    	{ 
    		get { return _historyID; } 
    		set { SetProperty(ref _historyID, value); } 
    	}
    
        private System.DateTime _week;
    	public System.DateTime Week 
    	{ 
    		get { return _week; } 
    		set { SetProperty(ref _week, value); } 
    	}
    
        private int _earnedValueTypeID;
    	public int EarnedValueTypeID 
    	{ 
    		get { return _earnedValueTypeID; } 
    		set { SetProperty(ref _earnedValueTypeID, value); } 
    	}
    
        private double _value;
    	public double Value 
    	{ 
    		get { return _value; } 
    		set { SetProperty(ref _value, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual tblProject_EarnedValueType tblProject_EarnedValueType { get; set; }
        public virtual tblProject_History tblProject_History { get; set; }
    }
}
