//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblProject_History : ModelBase
    {
        public tblProject_History()
        {
            this.tblProject_HistoryCritical = new HashSet<tblProject_HistoryCritical>();
            this.tblProject_HistoryManHours = new HashSet<tblProject_HistoryManHours>();
            this.tblProject_HistoryMilestone = new HashSet<tblProject_HistoryMilestone>();
        }
    
        private int _historyID;
    	public int HistoryID 
    	{ 
    		get { return _historyID; } 
    		set { SetProperty(ref _historyID, value); } 
    	}
    
        private int _projectID;
    	public int ProjectID 
    	{ 
    		get { return _projectID; } 
    		set { SetProperty(ref _projectID, value); } 
    	}
    
        private System.DateTime _period;
    	public System.DateTime Period 
    	{ 
    		get { return _period; } 
    		set { SetProperty(ref _period, value); } 
    	}
    
        private string _aXProjectID;
    	public string AXProjectID 
    	{ 
    		get { return _aXProjectID; } 
    		set { SetProperty(ref _aXProjectID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private string _status;
    	public string Status 
    	{ 
    		get { return _status; } 
    		set { SetProperty(ref _status, value); } 
    	}
    
        private Nullable<int> _grossProfit;
    	public Nullable<int> GrossProfit 
    	{ 
    		get { return _grossProfit; } 
    		set { SetProperty(ref _grossProfit, value); } 
    	}
    
        private string _aXJobNo;
    	public string AXJobNo 
    	{ 
    		get { return _aXJobNo; } 
    		set { SetProperty(ref _aXJobNo, value); } 
    	}
    
        private string _contractType;
    	public string ContractType 
    	{ 
    		get { return _contractType; } 
    		set { SetProperty(ref _contractType, value); } 
    	}
    
        private string _client;
    	public string Client 
    	{ 
    		get { return _client; } 
    		set { SetProperty(ref _client, value); } 
    	}
    
        private Nullable<System.DateTime> _date;
    	public Nullable<System.DateTime> Date 
    	{ 
    		get { return _date; } 
    		set { SetProperty(ref _date, value); } 
    	}
    
        private Nullable<System.DateTime> _weekEnding;
    	public Nullable<System.DateTime> WeekEnding 
    	{ 
    		get { return _weekEnding; } 
    		set { SetProperty(ref _weekEnding, value); } 
    	}
    
        private Nullable<System.DateTime> _keyDatesAward;
    	public Nullable<System.DateTime> KeyDatesAward 
    	{ 
    		get { return _keyDatesAward; } 
    		set { SetProperty(ref _keyDatesAward, value); } 
    	}
    
        private Nullable<System.DateTime> _keyDatesOriginalPC;
    	public Nullable<System.DateTime> KeyDatesOriginalPC 
    	{ 
    		get { return _keyDatesOriginalPC; } 
    		set { SetProperty(ref _keyDatesOriginalPC, value); } 
    	}
    
        private Nullable<System.DateTime> _keyDatesApprovedPC;
    	public Nullable<System.DateTime> KeyDatesApprovedPC 
    	{ 
    		get { return _keyDatesApprovedPC; } 
    		set { SetProperty(ref _keyDatesApprovedPC, value); } 
    	}
    
        private Nullable<System.DateTime> _keyDatesForecastPC;
    	public Nullable<System.DateTime> KeyDatesForecastPC 
    	{ 
    		get { return _keyDatesForecastPC; } 
    		set { SetProperty(ref _keyDatesForecastPC, value); } 
    	}
    
        private string _keyDatesRiskOpp;
    	public string KeyDatesRiskOpp 
    	{ 
    		get { return _keyDatesRiskOpp; } 
    		set { SetProperty(ref _keyDatesRiskOpp, value); } 
    	}
    
        private Nullable<int> _durationActual;
    	public Nullable<int> DurationActual 
    	{ 
    		get { return _durationActual; } 
    		set { SetProperty(ref _durationActual, value); } 
    	}
    
        private Nullable<int> _durationOriginal;
    	public Nullable<int> DurationOriginal 
    	{ 
    		get { return _durationOriginal; } 
    		set { SetProperty(ref _durationOriginal, value); } 
    	}
    
        private Nullable<int> _durationApproved;
    	public Nullable<int> DurationApproved 
    	{ 
    		get { return _durationApproved; } 
    		set { SetProperty(ref _durationApproved, value); } 
    	}
    
        private Nullable<int> _durationForecast;
    	public Nullable<int> DurationForecast 
    	{ 
    		get { return _durationForecast; } 
    		set { SetProperty(ref _durationForecast, value); } 
    	}
    
        private string _durationRiskOpp;
    	public string DurationRiskOpp 
    	{ 
    		get { return _durationRiskOpp; } 
    		set { SetProperty(ref _durationRiskOpp, value); } 
    	}
    
        private Nullable<int> _completeActual;
    	public Nullable<int> CompleteActual 
    	{ 
    		get { return _completeActual; } 
    		set { SetProperty(ref _completeActual, value); } 
    	}
    
        private Nullable<int> _completeBaseline;
    	public Nullable<int> CompleteBaseline 
    	{ 
    		get { return _completeBaseline; } 
    		set { SetProperty(ref _completeBaseline, value); } 
    	}
    
        private Nullable<int> _completeApprovedBaseline;
    	public Nullable<int> CompleteApprovedBaseline 
    	{ 
    		get { return _completeApprovedBaseline; } 
    		set { SetProperty(ref _completeApprovedBaseline, value); } 
    	}
    
        private Nullable<int> _completeForecast;
    	public Nullable<int> CompleteForecast 
    	{ 
    		get { return _completeForecast; } 
    		set { SetProperty(ref _completeForecast, value); } 
    	}
    
        private string _completeRiskOpp;
    	public string CompleteRiskOpp 
    	{ 
    		get { return _completeRiskOpp; } 
    		set { SetProperty(ref _completeRiskOpp, value); } 
    	}
    
        private int _statusID;
    	public int StatusID 
    	{ 
    		get { return _statusID; } 
    		set { SetProperty(ref _statusID, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
        private string _statusActionsTaken;
    	public string StatusActionsTaken 
    	{ 
    		get { return _statusActionsTaken; } 
    		set { SetProperty(ref _statusActionsTaken, value); } 
    	}
    
        private string _resourcesPFRiskOpp;
    	public string ResourcesPFRiskOpp 
    	{ 
    		get { return _resourcesPFRiskOpp; } 
    		set { SetProperty(ref _resourcesPFRiskOpp, value); } 
    	}
    
        private string _resourcesEACRiskOpp;
    	public string ResourcesEACRiskOpp 
    	{ 
    		get { return _resourcesEACRiskOpp; } 
    		set { SetProperty(ref _resourcesEACRiskOpp, value); } 
    	}
    
        private Nullable<double> _summaryContractValueOriginal;
    	public Nullable<double> SummaryContractValueOriginal 
    	{ 
    		get { return _summaryContractValueOriginal; } 
    		set { SetProperty(ref _summaryContractValueOriginal, value); } 
    	}
    
        private Nullable<double> _summaryContactValueApproved;
    	public Nullable<double> SummaryContactValueApproved 
    	{ 
    		get { return _summaryContactValueApproved; } 
    		set { SetProperty(ref _summaryContactValueApproved, value); } 
    	}
    
        private string _summaryContactValueRiskOpp;
    	public string SummaryContactValueRiskOpp 
    	{ 
    		get { return _summaryContactValueRiskOpp; } 
    		set { SetProperty(ref _summaryContactValueRiskOpp, value); } 
    	}
    
        private Nullable<double> _summaryAtCompletionBudget;
    	public Nullable<double> SummaryAtCompletionBudget 
    	{ 
    		get { return _summaryAtCompletionBudget; } 
    		set { SetProperty(ref _summaryAtCompletionBudget, value); } 
    	}
    
        private Nullable<double> _summaryAtCompletionEstimate;
    	public Nullable<double> SummaryAtCompletionEstimate 
    	{ 
    		get { return _summaryAtCompletionEstimate; } 
    		set { SetProperty(ref _summaryAtCompletionEstimate, value); } 
    	}
    
        private string _summaryAtCompletionRiskOpp;
    	public string SummaryAtCompletionRiskOpp 
    	{ 
    		get { return _summaryAtCompletionRiskOpp; } 
    		set { SetProperty(ref _summaryAtCompletionRiskOpp, value); } 
    	}
    
        private Nullable<double> _summaryCPI;
    	public Nullable<double> SummaryCPI 
    	{ 
    		get { return _summaryCPI; } 
    		set { SetProperty(ref _summaryCPI, value); } 
    	}
    
        private Nullable<double> _summarySPI;
    	public Nullable<double> SummarySPI 
    	{ 
    		get { return _summarySPI; } 
    		set { SetProperty(ref _summarySPI, value); } 
    	}
    
        private string _summarySPICPIRiskOpp;
    	public string SummarySPICPIRiskOpp 
    	{ 
    		get { return _summarySPICPIRiskOpp; } 
    		set { SetProperty(ref _summarySPICPIRiskOpp, value); } 
    	}
    
        private Nullable<double> _budgetBudget;
    	public Nullable<double> BudgetBudget 
    	{ 
    		get { return _budgetBudget; } 
    		set { SetProperty(ref _budgetBudget, value); } 
    	}
    
        private Nullable<double> _budgetPlanned;
    	public Nullable<double> BudgetPlanned 
    	{ 
    		get { return _budgetPlanned; } 
    		set { SetProperty(ref _budgetPlanned, value); } 
    	}
    
        private Nullable<double> _budgetEarned;
    	public Nullable<double> BudgetEarned 
    	{ 
    		get { return _budgetEarned; } 
    		set { SetProperty(ref _budgetEarned, value); } 
    	}
    
        private Nullable<double> _budgetActual;
    	public Nullable<double> BudgetActual 
    	{ 
    		get { return _budgetActual; } 
    		set { SetProperty(ref _budgetActual, value); } 
    	}
    
        private Nullable<double> _budgetCV;
    	public Nullable<double> BudgetCV 
    	{ 
    		get { return _budgetCV; } 
    		set { SetProperty(ref _budgetCV, value); } 
    	}
    
        private Nullable<double> _budgetSV;
    	public Nullable<double> BudgetSV 
    	{ 
    		get { return _budgetSV; } 
    		set { SetProperty(ref _budgetSV, value); } 
    	}
    
        private Nullable<double> _budgetCPI;
    	public Nullable<double> BudgetCPI 
    	{ 
    		get { return _budgetCPI; } 
    		set { SetProperty(ref _budgetCPI, value); } 
    	}
    
        private string _budgetRiskOpp;
    	public string BudgetRiskOpp 
    	{ 
    		get { return _budgetRiskOpp; } 
    		set { SetProperty(ref _budgetRiskOpp, value); } 
    	}
    
        private byte[] _statusGantt;
    	public byte[] StatusGantt 
    	{ 
    		get { return _statusGantt; } 
    		set { SetProperty(ref _statusGantt, value); } 
    	}
    
        private string _statusRiskOpp;
    	public string StatusRiskOpp 
    	{ 
    		get { return _statusRiskOpp; } 
    		set { SetProperty(ref _statusRiskOpp, value); } 
    	}
    
        private Nullable<double> _budgetContractTotal;
    	public Nullable<double> BudgetContractTotal 
    	{ 
    		get { return _budgetContractTotal; } 
    		set { SetProperty(ref _budgetContractTotal, value); } 
    	}
    
        private Nullable<double> _budgetContractMarginDollars;
    	public Nullable<double> BudgetContractMarginDollars 
    	{ 
    		get { return _budgetContractMarginDollars; } 
    		set { SetProperty(ref _budgetContractMarginDollars, value); } 
    	}
    
        private Nullable<double> _budgetContractMarginPercent;
    	public Nullable<double> BudgetContractMarginPercent 
    	{ 
    		get { return _budgetContractMarginPercent; } 
    		set { SetProperty(ref _budgetContractMarginPercent, value); } 
    	}
    
        private string _rFIForeseenIssuesActions;
    	public string RFIForeseenIssuesActions 
    	{ 
    		get { return _rFIForeseenIssuesActions; } 
    		set { SetProperty(ref _rFIForeseenIssuesActions, value); } 
    	}
    
        private string _qualityForeseenIssuesActions;
    	public string QualityForeseenIssuesActions 
    	{ 
    		get { return _qualityForeseenIssuesActions; } 
    		set { SetProperty(ref _qualityForeseenIssuesActions, value); } 
    	}
    
        private string _environmentForeseenIssuesActions;
    	public string EnvironmentForeseenIssuesActions 
    	{ 
    		get { return _environmentForeseenIssuesActions; } 
    		set { SetProperty(ref _environmentForeseenIssuesActions, value); } 
    	}
    
        private string _other;
    	public string Other 
    	{ 
    		get { return _other; } 
    		set { SetProperty(ref _other, value); } 
    	}
    
    
        public virtual tblProject_HistoryStatus tblProject_HistoryStatus { get; set; }
        public virtual ICollection<tblProject_HistoryCritical> tblProject_HistoryCritical { get; set; }
        public virtual ICollection<tblProject_HistoryManHours> tblProject_HistoryManHours { get; set; }
        public virtual ICollection<tblProject_HistoryMilestone> tblProject_HistoryMilestone { get; set; }
        public virtual tblProject tblProject { get; set; }
    }
}
