//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblProject_ContractType : ModelBase
    {
        public tblProject_ContractType()
        {
            this.tblProjects = new HashSet<tblProject>();
        }
    
        private int _contractTypeID;
    	public int ContractTypeID 
    	{ 
    		get { return _contractTypeID; } 
    		set { SetProperty(ref _contractTypeID, value); } 
    	}
    
        private string _aXDataAreaID;
    	public string AXDataAreaID 
    	{ 
    		get { return _aXDataAreaID; } 
    		set { SetProperty(ref _aXDataAreaID, value); } 
    	}
    
        private string _aXProjGroupID;
    	public string AXProjGroupID 
    	{ 
    		get { return _aXProjGroupID; } 
    		set { SetProperty(ref _aXProjGroupID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual ICollection<tblProject> tblProjects { get; set; }
    }
}
