//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblProject_Portfolio : ModelBase
    {
        public tblProject_Portfolio()
        {
            this.tblProjects = new HashSet<tblProject>();
        }
    
        private int _portfolioID;
    	public int PortfolioID 
    	{ 
    		get { return _portfolioID; } 
    		set { SetProperty(ref _portfolioID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private Nullable<int> _parentID;
    	public Nullable<int> ParentID 
    	{ 
    		get { return _parentID; } 
    		set { SetProperty(ref _parentID, value); } 
    	}
    
        private bool _canAllocate;
    	public bool CanAllocate 
    	{ 
    		get { return _canAllocate; } 
    		set { SetProperty(ref _canAllocate, value); } 
    	}
    
        private int _sortOrder;
    	public int SortOrder 
    	{ 
    		get { return _sortOrder; } 
    		set { SetProperty(ref _sortOrder, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual ICollection<tblProject> tblProjects { get; set; }
    }
}
