//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblProject_Project : ModelBase,IDataErrorInfo
    {
        private string _projectID;
    	public string ProjectID 
    	{ 
    		get { return _projectID; } 
    		set { SetProperty(ref _projectID, value); } 
    	}
    
        private string _description;
    	public string Description 
    	{ 
    		get { return _description; } 
    		set { SetProperty(ref _description, value); } 
    	}
    
        private string _managerID;
    	public string ManagerID 
    	{ 
    		get { return _managerID; } 
    		set { SetProperty(ref _managerID, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual tblPerson_Person tblPerson_Person { get; set; }
    }
}
