//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblPerson : ModelBase
    {
        public tblPerson()
        {
            this.tblProjects = new HashSet<tblProject>();
            this.tblProjects1 = new HashSet<tblProject>();
            this.tblTenders = new HashSet<tblTender>();
        }
    
        private int _personID;
    	public int PersonID 
    	{ 
    		get { return _personID; } 
    		set { SetProperty(ref _personID, value); } 
    	}
    
        private string _aXPersonID;
    	public string AXPersonID 
    	{ 
    		get { return _aXPersonID; } 
    		set { SetProperty(ref _aXPersonID, value); } 
    	}
    
        private string _aXDataAreaID;
    	public string AXDataAreaID 
    	{ 
    		get { return _aXDataAreaID; } 
    		set { SetProperty(ref _aXDataAreaID, value); } 
    	}
    
        private string _name;
    	public string Name 
    	{ 
    		get { return _name; } 
    		set { SetProperty(ref _name, value); } 
    	}
    
        private string _login;
    	public string Login 
    	{ 
    		get { return _login; } 
    		set { SetProperty(ref _login, value); } 
    	}
    
        private int _statusID;
    	public int StatusID 
    	{ 
    		get { return _statusID; } 
    		set { SetProperty(ref _statusID, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual ICollection<tblProject> tblProjects { get; set; }
        public virtual ICollection<tblProject> tblProjects1 { get; set; }
        public virtual ICollection<tblTender> tblTenders { get; set; }
    }
}
