//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblProject_HistoryRating : ModelBase
    {
        public tblProject_HistoryRating()
        {
            this.tblProject_History = new HashSet<tblProject_History>();
            this.tblProject_History1 = new HashSet<tblProject_History>();
            this.tblProject_History2 = new HashSet<tblProject_History>();
            this.tblProject_History3 = new HashSet<tblProject_History>();
            this.tblProject_History4 = new HashSet<tblProject_History>();
        }
    
        private int _ratingID;
    	public int RatingID 
    	{ 
    		get { return _ratingID; } 
    		set { SetProperty(ref _ratingID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private string _color;
    	public string Color 
    	{ 
    		get { return _color; } 
    		set { SetProperty(ref _color, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual ICollection<tblProject_History> tblProject_History { get; set; }
        public virtual ICollection<tblProject_History> tblProject_History1 { get; set; }
        public virtual ICollection<tblProject_History> tblProject_History2 { get; set; }
        public virtual ICollection<tblProject_History> tblProject_History3 { get; set; }
        public virtual ICollection<tblProject_History> tblProject_History4 { get; set; }
    }
}
