//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblProject_HistoryNCR : ModelBase
    {
        private int _historyID;
    	public int HistoryID 
    	{ 
    		get { return _historyID; } 
    		set { SetProperty(ref _historyID, value); } 
    	}
    
        private string _reportID;
    	public string ReportID 
    	{ 
    		get { return _reportID; } 
    		set { SetProperty(ref _reportID, value); } 
    	}
    
        private string _issuedToPerson;
    	public string IssuedToPerson 
    	{ 
    		get { return _issuedToPerson; } 
    		set { SetProperty(ref _issuedToPerson, value); } 
    	}
    
        private string _issuedToCompany;
    	public string IssuedToCompany 
    	{ 
    		get { return _issuedToCompany; } 
    		set { SetProperty(ref _issuedToCompany, value); } 
    	}
    
        private System.DateTime _dateRaised;
    	public System.DateTime DateRaised 
    	{ 
    		get { return _dateRaised; } 
    		set { SetProperty(ref _dateRaised, value); } 
    	}
    
        private string _eventDesc;
    	public string EventDesc 
    	{ 
    		get { return _eventDesc; } 
    		set { SetProperty(ref _eventDesc, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual tblProject_History tblProject_History { get; set; }
    }
}
