//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblProject_HistoryRFI : ModelBase
    {
        private int _historyID;
    	public int HistoryID 
    	{ 
    		get { return _historyID; } 
    		set { SetProperty(ref _historyID, value); } 
    	}
    
        private string _rFIID;
    	public string RFIID 
    	{ 
    		get { return _rFIID; } 
    		set { SetProperty(ref _rFIID, value); } 
    	}
    
        private string _raisedBy;
    	public string RaisedBy 
    	{ 
    		get { return _raisedBy; } 
    		set { SetProperty(ref _raisedBy, value); } 
    	}
    
        private System.DateTime _dateRaised;
    	public System.DateTime DateRaised 
    	{ 
    		get { return _dateRaised; } 
    		set { SetProperty(ref _dateRaised, value); } 
    	}
    
        private string _subject;
    	public string Subject 
    	{ 
    		get { return _subject; } 
    		set { SetProperty(ref _subject, value); } 
    	}
    
        private string _reference;
    	public string Reference 
    	{ 
    		get { return _reference; } 
    		set { SetProperty(ref _reference, value); } 
    	}
    
        private string _queryText;
    	public string QueryText 
    	{ 
    		get { return _queryText; } 
    		set { SetProperty(ref _queryText, value); } 
    	}
    
        private bool _emailSent;
    	public bool EmailSent 
    	{ 
    		get { return _emailSent; } 
    		set { SetProperty(ref _emailSent, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual tblProject_History tblProject_History { get; set; }
    }
}
