//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblTender_WorkgroupAdditionalHours : ModelBase
    {
        private int _additionalItemID;
    	public int AdditionalItemID 
    	{ 
    		get { return _additionalItemID; } 
    		set { SetProperty(ref _additionalItemID, value); } 
    	}
    
        private int _workgroupID;
    	public int WorkgroupID 
    	{ 
    		get { return _workgroupID; } 
    		set { SetProperty(ref _workgroupID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private double _count;
    	public double Count 
    	{ 
    		get { return _count; } 
    		set { SetProperty(ref _count, value); } 
    	}
    
        private double _hours;
    	public double Hours 
    	{ 
    		get { return _hours; } 
    		set { SetProperty(ref _hours, value); } 
    	}
    
        private string _comments;
    	public string Comments 
    	{ 
    		get { return _comments; } 
    		set { SetProperty(ref _comments, value); } 
    	}
    
        private int _sortOrder;
    	public int SortOrder 
    	{ 
    		get { return _sortOrder; } 
    		set { SetProperty(ref _sortOrder, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual tblTender_WorkGroup tblTender_WorkGroup { get; set; }
    }
}
