//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblTender_OverheadItem : ModelBase
    {
        private int _overheadItemID;
    	public int OverheadItemID 
    	{ 
    		get { return _overheadItemID; } 
    		set { SetProperty(ref _overheadItemID, value); } 
    	}
    
        private int _overheadID;
    	public int OverheadID 
    	{ 
    		get { return _overheadID; } 
    		set { SetProperty(ref _overheadID, value); } 
    	}
    
        private int _overheadGroupID;
    	public int OverheadGroupID 
    	{ 
    		get { return _overheadGroupID; } 
    		set { SetProperty(ref _overheadGroupID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private double _count;
    	public double Count 
    	{ 
    		get { return _count; } 
    		set { SetProperty(ref _count, value); } 
    	}
    
        private double _duration;
    	public double Duration 
    	{ 
    		get { return _duration; } 
    		set { SetProperty(ref _duration, value); } 
    	}
    
        private double _rate;
    	public double Rate 
    	{ 
    		get { return _rate; } 
    		set { SetProperty(ref _rate, value); } 
    	}
    
        private string _comments;
    	public string Comments 
    	{ 
    		get { return _comments; } 
    		set { SetProperty(ref _comments, value); } 
    	}
    
        private int _sortOrder;
    	public int SortOrder 
    	{ 
    		get { return _sortOrder; } 
    		set { SetProperty(ref _sortOrder, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual tblTender_Overhead tblTender_Overhead { get; set; }
        public virtual tblTender_OverheadGroup tblTender_OverheadGroup { get; set; }
    }
}
