//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblTender_EstimateItem : ModelBase
    {
        private int _estimateItemID;
    	public int EstimateItemID 
    	{ 
    		get { return _estimateItemID; } 
    		set { SetProperty(ref _estimateItemID, value); } 
    	}
    
        private int _tenderID;
    	public int TenderID 
    	{ 
    		get { return _tenderID; } 
    		set { SetProperty(ref _tenderID, value); } 
    	}
    
        private int _scheduleID;
    	public int ScheduleID 
    	{ 
    		get { return _scheduleID; } 
    		set { SetProperty(ref _scheduleID, value); } 
    	}
    
        private int _estimateItemTypeID;
    	public int EstimateItemTypeID 
    	{ 
    		get { return _estimateItemTypeID; } 
    		set { SetProperty(ref _estimateItemTypeID, value); } 
    	}
    
        private int _workGroupID;
    	public int WorkGroupID 
    	{ 
    		get { return _workGroupID; } 
    		set { SetProperty(ref _workGroupID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private double _men;
    	public double Men 
    	{ 
    		get { return _men; } 
    		set { SetProperty(ref _men, value); } 
    	}
    
        private double _hoursPerDay;
    	public double HoursPerDay 
    	{ 
    		get { return _hoursPerDay; } 
    		set { SetProperty(ref _hoursPerDay, value); } 
    	}
    
        private double _days;
    	public double Days 
    	{ 
    		get { return _days; } 
    		set { SetProperty(ref _days, value); } 
    	}
    
        private int _subcontractorID;
    	public int SubcontractorID 
    	{ 
    		get { return _subcontractorID; } 
    		set { SetProperty(ref _subcontractorID, value); } 
    	}
    
        private double _subcontractorRate;
    	public double SubcontractorRate 
    	{ 
    		get { return _subcontractorRate; } 
    		set { SetProperty(ref _subcontractorRate, value); } 
    	}
    
        private int _unitOfMeasureID;
    	public int UnitOfMeasureID 
    	{ 
    		get { return _unitOfMeasureID; } 
    		set { SetProperty(ref _unitOfMeasureID, value); } 
    	}
    
        private double _quantity;
    	public double Quantity 
    	{ 
    		get { return _quantity; } 
    		set { SetProperty(ref _quantity, value); } 
    	}
    
        private int _materialTakeoffID;
    	public int MaterialTakeoffID 
    	{ 
    		get { return _materialTakeoffID; } 
    		set { SetProperty(ref _materialTakeoffID, value); } 
    	}
    
        private double _markup;
    	public double Markup 
    	{ 
    		get { return _markup; } 
    		set { SetProperty(ref _markup, value); } 
    	}
    
        private string _comment;
    	public string Comment 
    	{ 
    		get { return _comment; } 
    		set { SetProperty(ref _comment, value); } 
    	}
    
        private int _sortOrder;
    	public int SortOrder 
    	{ 
    		get { return _sortOrder; } 
    		set { SetProperty(ref _sortOrder, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual tblTender tblTender { get; set; }
        public virtual tblTender_Contractor tblTender_Contractor { get; set; }
        public virtual tblTender_Schedule tblTender_Schedule { get; set; }
        public virtual tblTender_UnitOfMeasure tblTender_UnitOfMeasure { get; set; }
        public virtual tblTender_WorkGroup tblTender_WorkGroup { get; set; }
        public virtual tblTender_EstimateItemType tblTender_EstimateItemType { get; set; }
    }
}
