//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblTender_Supplier_Material : ModelBase
    {
        private int _supplierID;
    	public int SupplierID 
    	{ 
    		get { return _supplierID; } 
    		set { SetProperty(ref _supplierID, value); } 
    	}
    
        private int _materialID;
    	public int MaterialID 
    	{ 
    		get { return _materialID; } 
    		set { SetProperty(ref _materialID, value); } 
    	}
    
        private double _unitOfMeasureRate;
    	public double UnitOfMeasureRate 
    	{ 
    		get { return _unitOfMeasureRate; } 
    		set { SetProperty(ref _unitOfMeasureRate, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual tblTender_Material tblTender_Material { get; set; }
        public virtual tblTender_Supplier tblTender_Supplier { get; set; }
    }
}
