//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblTender_Step : ModelBase
    {
        public tblTender_Step()
        {
            this.tblTender_ObjectChildObject = new HashSet<tblTender_ObjectChildObject>();
            this.tblTender_ObjectLabour = new HashSet<tblTender_ObjectLabour>();
            this.tblTender_ObjectContractor = new HashSet<tblTender_ObjectContractor>();
            this.tblTender_ObjectMaterial = new HashSet<tblTender_ObjectMaterial>();
        }
    
        private int _stepID;
    	public int StepID 
    	{ 
    		get { return _stepID; } 
    		set { SetProperty(ref _stepID, value); } 
    	}
    
        private int _tenderID;
    	public int TenderID 
    	{ 
    		get { return _tenderID; } 
    		set { SetProperty(ref _tenderID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private int _sortOrder;
    	public int SortOrder 
    	{ 
    		get { return _sortOrder; } 
    		set { SetProperty(ref _sortOrder, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual ICollection<tblTender_ObjectChildObject> tblTender_ObjectChildObject { get; set; }
        public virtual ICollection<tblTender_ObjectLabour> tblTender_ObjectLabour { get; set; }
        public virtual ICollection<tblTender_ObjectContractor> tblTender_ObjectContractor { get; set; }
        public virtual ICollection<tblTender_ObjectMaterial> tblTender_ObjectMaterial { get; set; }
    }
}
