//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTender_ActivityContractor
    {
        public int ActivityContractorID { get; set; }
        public int ActivityID { get; set; }
        public string Title { get; set; }
        public int StepID { get; set; }
        public int ContractorID { get; set; }
        public double Quantity { get; set; }
        public double Rate { get; set; }
        public double MarkUp { get; set; }
        public string Comment { get; set; }
        public double SortOrder { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual tblTender_Activity tblTender_Activity { get; set; }
        public virtual tblTender_Step tblTender_Step { get; set; }
        public virtual tblTender_Contractor tblTender_Contractor { get; set; }
    }
}
