//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTender_ActivityLabour
    {
        public int ActivityLabourID { get; set; }
        public int ActivityID { get; set; }
        public int LabourStandardID { get; set; }
        public string Title { get; set; }
        public int StepID { get; set; }
        public int WorkgroupID { get; set; }
        public double Hours { get; set; }
        public double Men { get; set; }
        public int UnitOfMeasureID { get; set; }
        public double Quantity { get; set; }
        public string Comment { get; set; }
        public double SortOrder { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblTender_Activity tblTender_Activity { get; set; }
        public virtual tblTender_Step tblTender_Step { get; set; }
        public virtual tblTender_UnitOfMeasure tblTender_UnitOfMeasure { get; set; }
        public virtual tblTender_WorkGroup tblTender_WorkGroup { get; set; }
    }
}
