//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTender_Material
    {
        public tblTender_Material()
        {
            this.tblTender_ActivityMaterial = new HashSet<tblTender_ActivityMaterial>();
            this.tblTender_Supplier_Material = new HashSet<tblTender_Supplier_Material>();
        }
    
        public int MaterialID { get; set; }
        public int TenderID { get; set; }
        public string Title { get; set; }
        public double SQM { get; set; }
        public double KG { get; set; }
        public int UnitOfMeasureID { get; set; }
        public string Comment { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblTender tblTender { get; set; }
        public virtual ICollection<tblTender_ActivityMaterial> tblTender_ActivityMaterial { get; set; }
        public virtual tblTender_UnitOfMeasure tblTender_UnitOfMeasure { get; set; }
        public virtual ICollection<tblTender_Supplier_Material> tblTender_Supplier_Material { get; set; }
    }
}
