//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblTender_Overhead : ModelBase
    {
        public tblTender_Overhead()
        {
            this.tblTender_OverheadItem = new HashSet<tblTender_OverheadItem>();
            this.tblTender_ObjectLabour = new HashSet<tblTender_ObjectLabour>();
        }
    
        private int _overheadID;
    	public int OverheadID 
    	{ 
    		get { return _overheadID; } 
    		set { SetProperty(ref _overheadID, value); } 
    	}
    
        private int _tenderID;
    	public int TenderID 
    	{ 
    		get { return _tenderID; } 
    		set { SetProperty(ref _tenderID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private double _onsiteLabourRate;
    	public double OnsiteLabourRate 
    	{ 
    		get { return _onsiteLabourRate; } 
    		set { SetProperty(ref _onsiteLabourRate, value); } 
    	}
    
        private double _labourMarkup;
    	public double LabourMarkup 
    	{ 
    		get { return _labourMarkup; } 
    		set { SetProperty(ref _labourMarkup, value); } 
    	}
    
        private int _rate;
    	public int Rate 
    	{ 
    		get { return _rate; } 
    		set { SetProperty(ref _rate, value); } 
    	}
    
        private string _comment;
    	public string Comment 
    	{ 
    		get { return _comment; } 
    		set { SetProperty(ref _comment, value); } 
    	}
    
        private int _sortOrder;
    	public int SortOrder 
    	{ 
    		get { return _sortOrder; } 
    		set { SetProperty(ref _sortOrder, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual tblTender tblTender { get; set; }
        public virtual ICollection<tblTender_OverheadItem> tblTender_OverheadItem { get; set; }
        public virtual ICollection<tblTender_ObjectLabour> tblTender_ObjectLabour { get; set; }
    }
}
