//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTender_Supplier_Material
    {
        public int SupplierID { get; set; }
        public int MaterialID { get; set; }
        public double UnitOfMeasureRate { get; set; }
    
        public virtual tblTender_Material tblTender_Material { get; set; }
        public virtual tblTender_Supplier tblTender_Supplier { get; set; }
    }
}
