//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblTender_Object : ModelBase
    {
        public tblTender_Object()
        {
            this.tblTender_ObjectContractor = new HashSet<tblTender_ObjectContractor>();
            this.tblTender_ObjectChildObject = new HashSet<tblTender_ObjectChildObject>();
            this.tblTender_ObjectChildObject1 = new HashSet<tblTender_ObjectChildObject>();
            this.tblTender_Item = new HashSet<tblTender_Item>();
            this.tblTender_ObjectMaterial = new HashSet<tblTender_ObjectMaterial>();
            this.tblTender_ObjectLabour = new HashSet<tblTender_ObjectLabour>();
        }
    
        private int _objectID;
    	public int ObjectID 
    	{ 
    		get { return _objectID; } 
    		set { SetProperty(ref _objectID, value); } 
    	}
    
        private int _typeID;
    	public int TypeID 
    	{ 
    		get { return _typeID; } 
    		set { SetProperty(ref _typeID, value); } 
    	}
    
        private int _tenderID;
    	public int TenderID 
    	{ 
    		get { return _tenderID; } 
    		set { SetProperty(ref _tenderID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private int _unitOfMeasureID;
    	public int UnitOfMeasureID 
    	{ 
    		get { return _unitOfMeasureID; } 
    		set { SetProperty(ref _unitOfMeasureID, value); } 
    	}
    
        private string _comment;
    	public string Comment 
    	{ 
    		get { return _comment; } 
    		set { SetProperty(ref _comment, value); } 
    	}
    
        private int _sortOrder;
    	public int SortOrder 
    	{ 
    		get { return _sortOrder; } 
    		set { SetProperty(ref _sortOrder, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual tblTender tblTender { get; set; }
        public virtual tblTender_UnitOfMeasure tblTender_UnitOfMeasure { get; set; }
        public virtual ICollection<tblTender_ObjectContractor> tblTender_ObjectContractor { get; set; }
        public virtual ICollection<tblTender_ObjectChildObject> tblTender_ObjectChildObject { get; set; }
        public virtual ICollection<tblTender_ObjectChildObject> tblTender_ObjectChildObject1 { get; set; }
        public virtual ICollection<tblTender_Item> tblTender_Item { get; set; }
        public virtual tblTender_ObjectType tblTender_ObjectType { get; set; }
        public virtual ICollection<tblTender_ObjectMaterial> tblTender_ObjectMaterial { get; set; }
        public virtual ICollection<tblTender_ObjectLabour> tblTender_ObjectLabour { get; set; }
    }
}
