//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblTender_ObjectMaterial : ModelBase
    {
        private int _activityMaterialID;
    	public int ActivityMaterialID 
    	{ 
    		get { return _activityMaterialID; } 
    		set { SetProperty(ref _activityMaterialID, value); } 
    	}
    
        private int _activityID;
    	public int ActivityID 
    	{ 
    		get { return _activityID; } 
    		set { SetProperty(ref _activityID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private int _stepID;
    	public int StepID 
    	{ 
    		get { return _stepID; } 
    		set { SetProperty(ref _stepID, value); } 
    	}
    
        private int _materialID;
    	public int MaterialID 
    	{ 
    		get { return _materialID; } 
    		set { SetProperty(ref _materialID, value); } 
    	}
    
        private int _supplierID;
    	public int SupplierID 
    	{ 
    		get { return _supplierID; } 
    		set { SetProperty(ref _supplierID, value); } 
    	}
    
        private double _length;
    	public double Length 
    	{ 
    		get { return _length; } 
    		set { SetProperty(ref _length, value); } 
    	}
    
        private double _width;
    	public double Width 
    	{ 
    		get { return _width; } 
    		set { SetProperty(ref _width, value); } 
    	}
    
        private string _grade;
    	public string Grade 
    	{ 
    		get { return _grade; } 
    		set { SetProperty(ref _grade, value); } 
    	}
    
        private int _quantity;
    	public int Quantity 
    	{ 
    		get { return _quantity; } 
    		set { SetProperty(ref _quantity, value); } 
    	}
    
        private double _markup;
    	public double Markup 
    	{ 
    		get { return _markup; } 
    		set { SetProperty(ref _markup, value); } 
    	}
    
        private string _comment;
    	public string Comment 
    	{ 
    		get { return _comment; } 
    		set { SetProperty(ref _comment, value); } 
    	}
    
        private double _sortOrder;
    	public double SortOrder 
    	{ 
    		get { return _sortOrder; } 
    		set { SetProperty(ref _sortOrder, value); } 
    	}
    
        private string _updatedBy;
    	public string UpdatedBy 
    	{ 
    		get { return _updatedBy; } 
    		set { SetProperty(ref _updatedBy, value); } 
    	}
    
        private Nullable<System.DateTime> _updatedDate;
    	public Nullable<System.DateTime> UpdatedDate 
    	{ 
    		get { return _updatedDate; } 
    		set { SetProperty(ref _updatedDate, value); } 
    	}
    
        private byte[] _rowVersion;
    	public byte[] RowVersion 
    	{ 
    		get { return _rowVersion; } 
    		set { SetProperty(ref _rowVersion, value); } 
    	}
    
    
        public virtual tblTender_Material tblTender_Material { get; set; }
        public virtual tblTender_Object tblTender_Object { get; set; }
        public virtual tblTender_Step tblTender_Step { get; set; }
        public virtual tblTender_Supplier tblTender_Supplier { get; set; }
    }
}
