//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblWEX_Tree : ModelBase
    {
        public tblWEX_Tree()
        {
            this.tblWEX_NTSecurityGroup = new HashSet<tblWEX_NTSecurityGroup>();
        }
    
        private string _treeID;
    	public string TreeID 
    	{ 
    		get { return _treeID; } 
    		set { SetProperty(ref _treeID, value); } 
    	}
    
        private string _lHSTabID;
    	public string LHSTabID 
    	{ 
    		get { return _lHSTabID; } 
    		set { SetProperty(ref _lHSTabID, value); } 
    	}
    
        private int _order;
    	public int Order 
    	{ 
    		get { return _order; } 
    		set { SetProperty(ref _order, value); } 
    	}
    
        private string _rootSQL;
    	public string RootSQL 
    	{ 
    		get { return _rootSQL; } 
    		set { SetProperty(ref _rootSQL, value); } 
    	}
    
    
        public virtual tblWEX_LHSTab tblWEX_LHSTab { get; set; }
        public virtual ICollection<tblWEX_NTSecurityGroup> tblWEX_NTSecurityGroup { get; set; }
    }
}
