//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblWEX_NTSecurityGroup : ModelBase,IDataErrorInfo
    {
        public tblWEX_NTSecurityGroup()
        {
            this.tblWEX_RHSTab = new HashSet<tblWEX_RHSTab>();
            this.tblWEX_Tree = new HashSet<tblWEX_Tree>();
        }
    
        private string _nTSecurityGroup;
    	public string NTSecurityGroup 
    	{ 
    		get { return _nTSecurityGroup; } 
    		set { SetProperty(ref _nTSecurityGroup, value); } 
    	}
    
    
        public virtual ICollection<tblWEX_RHSTab> tblWEX_RHSTab { get; set; }
        public virtual ICollection<tblWEX_Tree> tblWEX_Tree { get; set; }
    }
}
