//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblWEX_TreeNodeType_RHSTab : ModelBase
    {
        private string _treeNodeTypeID;
    	public string TreeNodeTypeID 
    	{ 
    		get { return _treeNodeTypeID; } 
    		set { SetProperty(ref _treeNodeTypeID, value); } 
    	}
    
        private string _rHSTabID;
    	public string RHSTabID 
    	{ 
    		get { return _rHSTabID; } 
    		set { SetProperty(ref _rHSTabID, value); } 
    	}
    
        private int _tabOrder;
    	public int TabOrder 
    	{ 
    		get { return _tabOrder; } 
    		set { SetProperty(ref _tabOrder, value); } 
    	}
    
        private string _tabTitle;
    	public string TabTitle 
    	{ 
    		get { return _tabTitle; } 
    		set { SetProperty(ref _tabTitle, value); } 
    	}
    
    
        public virtual tblWEX_RHSTab tblWEX_RHSTab { get; set; }
        public virtual tblWEX_TreeNodeType tblWEX_TreeNodeType { get; set; }
    }
}
