//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblWEX_TreeNodeType : ModelBase
    {
        public tblWEX_TreeNodeType()
        {
            this.tblWEX_RHSTab = new HashSet<tblWEX_RHSTab>();
        }
    
        private string _treeNodeTypeID;
    	public string TreeNodeTypeID 
    	{ 
    		get { return _treeNodeTypeID; } 
    		set { SetProperty(ref _treeNodeTypeID, value); } 
    	}
    
    
        public virtual ICollection<tblWEX_RHSTab> tblWEX_RHSTab { get; set; }
    }
}
