//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWEX_LHSTab
    {
        public tblWEX_LHSTab()
        {
            this.tblWEX_Tree = new HashSet<tblWEX_Tree>();
        }
    
        public string LHSTabID { get; set; }
    
        public virtual ICollection<tblWEX_Tree> tblWEX_Tree { get; set; }
    }
}
