//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class tblWEX_Variables : ModelBase
    {
        private string _section;
    	public string Section 
    	{ 
    		get { return _section; } 
    		set { SetProperty(ref _section, value); } 
    	}
    
        private string _variable;
    	public string Variable 
    	{ 
    		get { return _variable; } 
    		set { SetProperty(ref _variable, value); } 
    	}
    
        private string _value;
    	public string Value 
    	{ 
    		get { return _value; } 
    		set { SetProperty(ref _value, value); } 
    	}
    
    }
}
