//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class vwProject_CostCodeIndirectView : ModelBase
    {
        private int _projectID;
    	public int ProjectID 
    	{ 
    		get { return _projectID; } 
    		set { SetProperty(ref _projectID, value); } 
    	}
    
        private string _aXProjectID;
    	public string AXProjectID 
    	{ 
    		get { return _aXProjectID; } 
    		set { SetProperty(ref _aXProjectID, value); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { SetProperty(ref _title, value); } 
    	}
    
        private bool _tempIsIndirect;
    	public bool TempIsIndirect 
    	{ 
    		get { return _tempIsIndirect; } 
    		set { SetProperty(ref _tempIsIndirect, value); } 
    	}
    
        private Nullable<int> _topParentID;
    	public Nullable<int> TopParentID 
    	{ 
    		get { return _topParentID; } 
    		set { SetProperty(ref _topParentID, value); } 
    	}
    
    }
}
