//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class vwTender_EstimateDetail : ModelBase
    {
        private int _tenderID;
    	public int TenderID 
    	{ 
    		get { return _tenderID; } 
    		set { SetProperty(ref _tenderID, value); } 
    	}
    
        private string _schedule;
    	public string Schedule 
    	{ 
    		get { return _schedule; } 
    		set { SetProperty(ref _schedule, value); } 
    	}
    
        private string _estimateItemType;
    	public string EstimateItemType 
    	{ 
    		get { return _estimateItemType; } 
    		set { SetProperty(ref _estimateItemType, value); } 
    	}
    
        private string _subcontractor;
    	public string Subcontractor 
    	{ 
    		get { return _subcontractor; } 
    		set { SetProperty(ref _subcontractor, value); } 
    	}
    
        private string _subcontractorType;
    	public string SubcontractorType 
    	{ 
    		get { return _subcontractorType; } 
    		set { SetProperty(ref _subcontractorType, value); } 
    	}
    
        private string _supplier;
    	public string Supplier 
    	{ 
    		get { return _supplier; } 
    		set { SetProperty(ref _supplier, value); } 
    	}
    
        private string _workGroup;
    	public string WorkGroup 
    	{ 
    		get { return _workGroup; } 
    		set { SetProperty(ref _workGroup, value); } 
    	}
    
        private string _drawing;
    	public string Drawing 
    	{ 
    		get { return _drawing; } 
    		set { SetProperty(ref _drawing, value); } 
    	}
    
        private string _material;
    	public string Material 
    	{ 
    		get { return _material; } 
    		set { SetProperty(ref _material, value); } 
    	}
    
        private double _hours;
    	public double Hours 
    	{ 
    		get { return _hours; } 
    		set { SetProperty(ref _hours, value); } 
    	}
    
        private double _cost;
    	public double Cost 
    	{ 
    		get { return _cost; } 
    		set { SetProperty(ref _cost, value); } 
    	}
    
    }
}
