//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    public partial class vwTender_ObjectHoursByWorkGroup : ModelBase
    {
        private Nullable<int> _tenderID;
    	public Nullable<int> TenderID 
    	{ 
    		get { return _tenderID; } 
    		set { SetProperty(ref _tenderID, value); } 
    	}
    
        private Nullable<int> _objectID;
    	public Nullable<int> ObjectID 
    	{ 
    		get { return _objectID; } 
    		set { SetProperty(ref _objectID, value); } 
    	}
    
        private string _objectName;
    	public string ObjectName 
    	{ 
    		get { return _objectName; } 
    		set { SetProperty(ref _objectName, value); } 
    	}
    
        private int _workGroupID;
    	public int WorkGroupID 
    	{ 
    		get { return _workGroupID; } 
    		set { SetProperty(ref _workGroupID, value); } 
    	}
    
        private string _workGroup;
    	public string WorkGroup 
    	{ 
    		get { return _workGroup; } 
    		set { SetProperty(ref _workGroup, value); } 
    	}
    
        private double _labourHours;
    	public double LabourHours 
    	{ 
    		get { return _labourHours; } 
    		set { SetProperty(ref _labourHours, value); } 
    	}
    
    }
}
