//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTender
    {
        public tblTender()
        {
            this.tblTender_Activity = new HashSet<tblTender_Activity>();
            this.tblTender_ContractorType = new HashSet<tblTender_ContractorType>();
            this.tblTender_Drawing = new HashSet<tblTender_Drawing>();
            this.tblTender_Item = new HashSet<tblTender_Item>();
            this.tblTender_LabourStandard = new HashSet<tblTender_LabourStandard>();
            this.tblTender_Material = new HashSet<tblTender_Material>();
            this.tblTender_Supplier = new HashSet<tblTender_Supplier>();
            this.tblTender_UnitOfMeasure = new HashSet<tblTender_UnitOfMeasure>();
            this.tblTender_WorkGroup = new HashSet<tblTender_WorkGroup>();
            this.tblTender_Contractor = new HashSet<tblTender_Contractor>();
        }
    
        public int TenderID { get; set; }
        public string TenderNo { get; set; }
        public string Revision { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
        public int StatusID { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<tblTender_Activity> tblTender_Activity { get; set; }
        public virtual ICollection<tblTender_ContractorType> tblTender_ContractorType { get; set; }
        public virtual ICollection<tblTender_Drawing> tblTender_Drawing { get; set; }
        public virtual ICollection<tblTender_Item> tblTender_Item { get; set; }
        public virtual ICollection<tblTender_LabourStandard> tblTender_LabourStandard { get; set; }
        public virtual ICollection<tblTender_Material> tblTender_Material { get; set; }
        public virtual ICollection<tblTender_Supplier> tblTender_Supplier { get; set; }
        public virtual tblTender_Status tblTender_Status { get; set; }
        public virtual ICollection<tblTender_UnitOfMeasure> tblTender_UnitOfMeasure { get; set; }
        public virtual ICollection<tblTender_WorkGroup> tblTender_WorkGroup { get; set; }
        public virtual ICollection<tblTender_Contractor> tblTender_Contractor { get; set; }
    }
}
