//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTender_WorkGroupItem
    {
        public int WorkGroupItemID { get; set; }
        public int WorkGroupID { get; set; }
        public int WorkGroupHeaderID { get; set; }
        public string Title { get; set; }
        public double Count { get; set; }
        public double Duration { get; set; }
        public double Rate { get; set; }
        public string Comments { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual tblTender_WorkGroup tblTender_WorkGroup { get; set; }
        public virtual tblTender_WorkGroupHeader tblTender_WorkGroupHeader { get; set; }
    }
}
