//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalzExplorer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTender_Activity
    {
        public tblTender_Activity()
        {
            this.tblTender_ActivityContractor = new HashSet<tblTender_ActivityContractor>();
            this.tblTender_ActivityLabour = new HashSet<tblTender_ActivityLabour>();
            this.tblTender_ActivityMaterial = new HashSet<tblTender_ActivityMaterial>();
            this.tblTender_ActivityChildActivity = new HashSet<tblTender_ActivityChildActivity>();
            this.tblTender_ActivityChildActivity1 = new HashSet<tblTender_ActivityChildActivity>();
            this.tblTender_Item = new HashSet<tblTender_Item>();
        }
    
        public int ActivityID { get; set; }
        public int TenderID { get; set; }
        public string Title { get; set; }
        public int UnitOfMeasureID { get; set; }
        public string Comment { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual tblTender tblTender { get; set; }
        public virtual tblTender_UnitOfMeasure tblTender_UnitOfMeasure { get; set; }
        public virtual ICollection<tblTender_ActivityContractor> tblTender_ActivityContractor { get; set; }
        public virtual ICollection<tblTender_ActivityLabour> tblTender_ActivityLabour { get; set; }
        public virtual ICollection<tblTender_ActivityMaterial> tblTender_ActivityMaterial { get; set; }
        public virtual ICollection<tblTender_ActivityChildActivity> tblTender_ActivityChildActivity { get; set; }
        public virtual ICollection<tblTender_ActivityChildActivity> tblTender_ActivityChildActivity1 { get; set; }
        public virtual ICollection<tblTender_Item> tblTender_Item { get; set; }
    }
}
